<?php declare(strict_types=1);

namespace Cspray\Labrador\AsyncUnit\Event;

use Cspray\Labrador\AsyncEvent\Event;
use Cspray\Labrador\AsyncEvent\StandardEvent;
use Cspray\Labrador\AsyncUnit\Events;
use Cspray\Labrador\AsyncUnit\Model\TestCaseModel;
use Cspray\Labrador\AsyncUnit\TestCase;

class TestCaseFinishedEvent extends StandardEvent implements Event {

    public function __construct(TestCaseModel $target) {
        parent::__construct(Events::TEST_CASE_FINISHED, $target);
    }

    public function getTarget() : TestCaseModel {
        return parent::getTarget(); // TODO: Change the autogenerated stub
    }

}