<?php declare(strict_types=1);

namespace Cspray\Labrador\AsyncUnit\Event;

use Cspray\Labrador\AsyncEvent\Event;
use Cspray\Labrador\AsyncEvent\StandardEvent;
use Cspray\Labrador\AsyncUnit\Events;
use Cspray\Labrador\AsyncUnit\Model\TestCaseModel;
use Cspray\Labrador\AsyncUnit\Statistics\ProcessedTestCaseSummary;

final class TestCaseFinishedEvent extends StandardEvent implements Event {

    public function __construct(ProcessedTestCaseSummary $testCaseSummary) {
        parent::__construct(Events::TEST_CASE_FINISHED, $testCaseSummary);
    }

    public function getTarget() : ProcessedTestCaseSummary {
        return parent::getTarget(); // TODO: Change the autogenerated stub
    }

}